version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./app:/app"
            - "./nginx:/nginx"
            - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/conf/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf"
            - "./nginx/conf/ssl-dhparams.pem:/etc/nginx/conf.d/ssl-dhparams.pem"
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - "./app:/app"
        links:
            - mysql
    mysql:
        image: mysql:latest
        ports:
            - "6606:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=moodle
            - MYSQL_USER=moodle
            - MYSQL_PASSWORD=moodle
        volumes:
            - mysql-data:/var/lib/mysql
    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
            - "./app:/app"
volumes:
    mysql-data:
